---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _domaines
  label: Domaines
  create: all
  match: "**/*"
  templates:
  - domaines
- type: directory
  path: _programmes
  label: Progammes
  create: all
  match: "**/*"
  templates:
  - programmes
- type: directory
  path: _commentaires
  label: Commentaires
  create: all
  match: "**/*"
  templates:
  - commentaires
- type: directory
  path: _partenaires
  label: Partenaires
  create: all
  match: "**/*"
  templates:
  - partenaires
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
